### PR TITLE
Fix screenshots on Mac (closes #78, closes #79)

### LINKED ISSUE #78: Executable permission flag on 'bin/mac/screenshot' is lost when publishing module on Windows
Screenshots are not working on OS X, because we are publishing module on Windows, and `x` flag (UNIX executable file permission flag) is not saved on binary `bin/mac/screenshot` in package tarball. So the binary can not be executed after module installation.

### LINKED ISSUE #79: Wrong thumbnail directory path on OS X
Looks like that before we specified the path to thumbnails directory for native module as a path, that is relative to the screenshots folder. But now we pass it as an absolute path, and it was changed for Windows native module, but not for Mac.

### PR DESCRIPTION
**Pull request by AndreyBelym**
* Fix file permissions on postinstall on Mac

 * Fix thumbnails directory path in Mac native screenshot module

\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by inikulin** [comment]
@AndreyBelym Can you publish latest version, please and update dependency in testcafe?

**Comment by AndreyBelym** [comment]
OK. But it's minor version change, so likely there is no need in updating dependencies.

**Comment by AndreyBelym** [comment]
Ooh, I've missed that https://github.com/DevExpress/testcafe/pull/645 is not merged yet, so I'll  update it to use `@0.14.1`.

**Pull request merged**
