### PR TITLE
Tweaked screenshot tool for Firefox on Windows 10 (closes #55)

### LINKED ISSUE #55: Firefox client area borders were changed on Windows 10
Firefox client area doesn't have bottom, right and left borders on Windows 10, so we need to modify our screenshot tool.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
@AndreyBelym Can you bump version in context of this PR, please?

**Comment by AndreyBelym** [comment]
No problem.

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
